# {abnt} Config File

Use this quarto document to change your thesis pre-textual sections in the PDF format.

**Do not remove the text tags**! (they look like this: `<!-- %:::% tag %:::% -->`)

Some general instructions:

- If you won't use a section of this document, remove it! Empty sections will produce an error. At the moment, you also need to remove them in the `tex/include-before-body.tex` file and `R/_pre-render-pdf.R`.

## Title page

<!-- %:::% title-page body begin %:::% -->
{\imprimirtipotrabalho} presented to the {\imprimirescola} at the {\imprimiruniversidade}, as a requirement for the degree of {\imprimirtituloacademico} by the {\imprimirprograma}.

\smallskip
Area of concentration: {\imprimirareadeconcentracao}

\smallskip
Supervisor: Prof. Dr. {\imprimirorientador}
<!-- %:::% title-page body end %:::% -->

## Cataloging record

<!-- %:::% cataloging-record body begin %:::% -->
I authorize the full or partial reproduction of this work by any conventional or electronic means for the purposes of study and research, provided that the source is cited.

\vfill
\begin{center}
Cataloging in publication

Library

{\imprimirescola}

\medskip
\ABNTEXfontereduzida
\setlength{\fboxsep}{1cm}
\fbox{
\begin{minipage}[c][6cm]{12cm}
Sales, Alícia Rafaelly Vilefort

\hspace{0.5cm} {\imprimirtitulo}  / {\imprimirautor} ; supervisor, {\imprimirorientador}. -- {\imprimirdata}

\hspace{0.5cm} {\thelastpage} p : il.

\smallskip
\hspace{0.5cm} {\imprimirtipotrabalho} (\imprimirtituloacademico) -- {\imprimirprograma}, {\imprimirescola}, {\imprimiruniversidade}.

\hspace{0.5cm} {\imprimirnotadeversao}.

\smallskip
\hspace{0.5cm} 1. Pregnancy. 2. Sleep. 3. Childbirth. 4. Chronobiology. 5. Midwifery. I. Chofakian, Christiane Borges do Nascimento, super. II. Title.

\end{minipage}
}
\end{center}
\vspace{\hugeskipamount}
<!-- %:::% cataloging-record body end %:::% -->

## Approval sheet header

<!-- %:::% approval-sheet body begin %:::% -->
{\imprimirtipotrabalho} by {\imprimirautor}, under the title \textbf{\imprimirtitulo}, presented to the {\imprimirescola} at the {\imprimiruniversidade}, as a requirement for the degree of {\imprimirtituloacademico} by the {\imprimirprograma}, in the concentration area of {\imprimirareadeconcentracao}.

\vspace{\hugeskipamount}
Approved on Month, Day Year.

\vspace{\hugeskipamount}
\begin{center}
  Examination Committee
\end{center}

\vspace{\smallskipamount}
Committee Chair:

\vspace{\tinyskipamount}
\begingroup

\AtBeginEnvironment{tabular}{
  \normalsize\raggedright
  \renewcommand{\arraystretch}{2}
}

\setlength{\arrayrulewidth}{0pt}
\setlength{\tabcolsep}{0cm}
\begin{tabular}{m{2.5cm} m{13.5cm}}
  Prof. Dr. &  \\
  Institution &  \\
\end{tabular}

\vspace{\bigskipamount}
Examiners:

\vspace{\tinyskipamount}
\begin{tabular}{m{2.5cm} m{13.5cm}}
  Prof. Dr. &  \\
  Institution &  \\
  Evaluation &  \\
\end{tabular}

\vspace{\smallskipamount}
\begin{tabular}{m{2.5cm} m{13.5cm}}
  Prof. Dr. &  \\
  Institution &  \\
  Evaluation &  \\
\end{tabular}

\vspace{\smallskipamount}
\begin{tabular}{m{2.5cm} m{13.5cm}}
  Prof. Dr. &  \\
  Institution &  \\
  Evaluation &  \\
\end{tabular}
\endgroup
<!-- %:::% approval-sheet body end %:::% -->

## Other "In Header" Additions

<!-- %:::% other-in-header begin %:::% -->
\definecolor{brand-primary}{HTML}{63483E}
\definecolor{brand-black}{HTML}{63483E}

\newcommand{\brandprimary}[1]{
  \textcolor{brand-primary}{#1}
}

\newcommand{\brandblack}[1]{
  \textcolor{brand-black}{#1}
}
<!-- %:::% other-in-header end %:::% -->

## Other "Before Body" Additions

<!-- %:::% other-before-body begin %:::% -->
<!-- %:::% other-before-body end %:::% -->

## Other "After Body" Additions

<!-- %:::% other-after-body begin %:::% -->
<!-- %:::% other-after-body end %:::% -->
