---
eval: false
---

<!-- %:::% .common h1 begin %:::% -->
# Appendice - Chronotype computation using actigraphy data
<!-- %:::% .common h1 end %:::% -->

```{r}
#| label: setup
#| include: false

source(here::here("R/quarto-setup.R"))
```

## Overview

This analysis aims to help to calculate the chronotype of a person based on his/her actipgrahy record.

## Setup

```{r}
#| eval: false

library(lubridate, quietly = TRUE)
library(lubritime, quietly = TRUE) # github.com/danielvartan/lubritime
library(hms, quietly = TRUE)
library(mctq, quietly = TRUE)
```

## Calculating the duration of an interval

```{r}
tz <- "America/Sao_Paulo"
start <- lubridate::dmy_hms("01/01/2023 05:00:00", tz = tz)
end <- lubridate::dmy_hms("02/07/2023 01:00:00", tz = tz)
start |>
lubridate::interval(end, tz = tz) |>
lubridate::as.period()
```

## Calculating the chronotype

```{r}
wd <- 6 # Número total de dias de trabalho
fd <- 17 # Número total de dias livres
# FPS nos dias de trabalho e dias livres
fps_w <- hms::parse_hms("07:01:10") |> lubridate::as.duration()
fps_f <- hms::parse_hms("07:24:31") |> lubridate::as.duration()
# HIS nos dias livres
his_f <- hms::parse_hms("01:55:42")
# Média ponderada do FPS
fps_weight_mean <- ((fps_w * wd) + (fps_f * fd)) / (wd + fd)
# Meio-sono nos dias livres corrigido (proxy do cronotipo)
msf <- mctq::msl(his_f, fps_f)
msf_sc <- mctq::msf_sc(msf, fps_w, fps_f, fps_weight_mean, FALSE)
lubritime::round_time(msf_sc)
```
