<!-- %:::% .common h1 begin %:::% -->
# Appendice - Anonymize and process files
<!-- %:::% .common h1 end %:::% -->

```{r}
#| label: setup
#| include: false

source(here::here("R/quarto-setup.R"))
```

## Overview

This notebook aim to normalize files from the project's vault.

**Make a copy of the vault before continuing!**

## Settings things up

```{r}
#| eval: false

library(checkmate)
library(googlesheets4)
library(prettycheck) # github.com/danielvartan/prettycheck
library(readr)
library(rutils) # github.com/danielvartan/rutils
library(sodium)
library(stringr)
```

```{r}
#| eval: false

source(here::here("R", "anonymize_id.R"))
source(here::here("R", "test_cpf.R"))
```

## Set parameters

```{r}
#| eval: false

password <- askpass::askpass()
```

```{r}
#| eval: false

salt <- askpass::askpass() # !Configure `salt` before running!
```

```{r}
#| eval: false

dir_vault <- utils::readClipboard() |> normalizePath("/", mustWork = FALSE)
```

```{r}
#| eval: false

dir_raw_data <- file.path(dir_vault, "raw-data")
dir_processed_data <- file.path(dir_vault, "processed-data")
dir_bundles <- file.path(dir_vault, "bundle")
```

```{r}
#| eval: false

dir_raw_actigraphy <- file.path(dir_raw_data, "actigraphy")
dir_raw_consent <- file.path(dir_raw_data, "consent")
dir_raw_control_form <- file.path(dir_raw_data, "control-form")
dir_raw_delivery_receipt <- file.path(dir_raw_data, "delivery-receipt")
dir_raw_field_form <- file.path(dir_raw_data, "field-form")
dir_raw_medical_record <- file.path(dir_raw_data, "medical-record")
dir_raw_pilot_form <- file.path(dir_raw_data, "pilot-form")
dir_raw_pregnancy_booklet <- file.path(dir_raw_data, "pregnancy-booklet")
dir_raw_return_receipt <- file.path(dir_raw_data, "return-receipt")
dir_raw_sleep_diary <- file.path(dir_raw_data, "sleep-diary")
```

```{r}
#| eval: false

# To Do: Add code to test if directories and files exist.
# 
# prettycheck:::assert_directory_exists()
# prettycheck:::assert_file_exists()
```

```{r}
#| eval: false

dir_processed_actigraphy <- file.path(dir_processed_data, "actigraphy")
dir_processed_sleep_diary <- file.path(dir_processed_data, "sleep-diary")
```

```{r}
#| eval: false

file_pilot_form <- file.path(dir_raw_pilot_form, "raw.csv")
file_field_form <- file.path(dir_raw_field_form, "raw.csv")
file_sleep_diary <- file.path(dir_raw_sleep_diary, "raw.csv")
file_control_form <- file.path(dir_raw_control_form, "raw.csv")
```

## Get data from Google Sheets

```{r}
#| eval: false
#| output: false

prettycheck:::assert_interactive()

googlesheets4::gs4_auth()
```

```{r}
#| eval: false

raw_data_pilot_form <- googlesheets4::read_sheet(
  ss = "19VvBMLL0EVk5345pLDdusEfI1WCZD1YfDjqmQnRgsuk",
  sheet = "Dataset",
  range = NULL,
  col_names = TRUE,
  col_types = "c",
  na = c("", "NA"),
  trim_ws = TRUE,
  skip = 0,
  n_max = Inf,
  .name_repair = "unique"
)

raw_data_pilot_form
```

```{r}
#| eval: false
#| output: false

raw_data_pilot_form |> readr::write_csv(file_pilot_form)
```

```{r}
#| eval: false

raw_data_field_form <- googlesheets4::read_sheet(
  ss = "1tY_TT0nPXFsErYQS2VED0-hqTzgHudA9BfhRhYG19fw",
  sheet = "Dataset",
  range = NULL,
  col_names = TRUE,
  col_types = "c",
  na = c("", "NA"),
  trim_ws = TRUE,
  skip = 0,
  n_max = Inf,
  .name_repair = "unique"
)

raw_data_field_form
```

```{r}
#| eval: false
#| output: false

raw_data_field_form |> readr::write_csv(file_field_form)
```

```{r}
#| eval: false

raw_data_sleep_diary <- googlesheets4::read_sheet(
  ss = "1VKJgS8ZrUO9E-yZ6WwfZgKNoEQWH7afk3K5jpAjgKxU",
  sheet = "Dataset",
  range = NULL,
  col_names = TRUE,
  col_types = "c",
  na = c("", "NA"),
  trim_ws = TRUE,
  skip = 0,
  n_max = Inf,
  .name_repair = "unique"
)

raw_data_sleep_diary
```

```{r}
#| eval: false
#| output: false

raw_data_sleep_diary |> readr::write_csv(file_sleep_diary)
```

```{r}
#| eval: false

raw_data_control_form <- googlesheets4::read_sheet(
  ss = "13wtDr4fRD1wJSM-qdLOdGSchF8oXU1bG0Jtccu24GhY",
  sheet = "Dataset",
  range = NULL,
  col_names = TRUE,
  col_types = "c",
  na = c("", "NA"),
  trim_ws = TRUE,
  skip = 0,
  n_max = Inf,
  .name_repair = "unique"
)

raw_data_control_form
```

```{r}
#| eval: false
#| output: false

raw_data_control_form |> readr::write_csv(file_control_form)
```

## Get CPF & anonimyzed IDs

```{r}
#| eval: false

cpf_values <- c(
  raw_data_pilot_form[[5]], 
  raw_data_field_form[[5]]
)

id_data <- dplyr::tibble(
  id = anonymize_id(cpf_values, salt = salt),
  cpf = cpf_values
) |>
  dplyr::distinct() |>
  dplyr::arrange(cpf)

id_data
```

```{r}
#| eval: false

test_cpf(id_data$cpf)
```

## Load, filter & write data

```{r}
#| eval: false

# For testing

i <- id_data |> dplyr::filter(id %in% "575f0b25")
# i <- id_data |> dplyr::filter(cpf %in% "45141075818")

i
```

```{r}
#| eval: false
#| output: false

for (i in split(id_data, seq(nrow(id_data)))) {
  raw_data_pilot_form_i <-
    raw_data_pilot_form |>
    scaler:::filter_data(col_index = 5, value = i$cpf) |>
    rutils:::shush()
  
  raw_data_field_form_i <-
    raw_data_field_form |>
    scaler:::filter_data(col_index = 5, value = i$cpf) |>
    rutils:::shush()

  if (nrow(raw_data_field_form_i) == 0 &&
      !nrow(raw_data_pilot_form_i) == 0) {
    raw_data_pilot_form_i |>
      readr::write_csv(
        file.path(
          dir_raw_pilot_form, 
          paste0(i$id, "_pilot-form", ".csv")
        )
      )
  }
  
  raw_data_sleep_diary_i <-
    raw_data_sleep_diary |>
    scaler:::filter_data(col_index = 3, value = i$cpf)

  if (!nrow(raw_data_field_form_i) == 0) {
    raw_data_field_form_i |>
      readr::write_csv(
        file.path(
          dir_raw_field_form, 
          paste0(i$id, "_field-form", ".csv")
        )
      )
  }

  if (!nrow(raw_data_sleep_diary_i) == 0) {
    sleep_diary_type_of_day_i <-
      raw_data_sleep_diary_i |>
      scaler:::get_sleep_diary_type_of_day(col_indexes = c(1, 4, 8, 10))

    tidy_data_sleep_diary_i <-
      raw_data_sleep_diary_i |>
      scaler:::tidy_sleep_diary(col_indexes = c(1, 8, 10, 19:28))
    
    raw_data_sleep_diary_i |>
      readr::write_csv(
        file.path(
          dir_raw_sleep_diary, 
          paste0(i$id, "_sleep-diary", ".csv")
        )
      )
  }
  
  if (!nrow(sleep_diary_type_of_day_i) == 0) {
    sleep_diary_type_of_day_i |>
      readr::write_csv(
        file.path(
          dir_processed_sleep_diary,
          paste0(i$id, "_sleep-diary-type-of-day", ".csv")
        )
      )
  }
  
  if (!nrow(sleep_diary_type_of_day_i) == 0) {
    tidy_data_sleep_diary_i |>
      scaler:::actstudio_sleep_diary(
        file = file.path(
          dir_processed_actigraphy,
          paste0(i$id, "_actigraphy-sleep-diary", ".txt")
        )
      )
  }
}
```

## Creating bundles

```{r}
#| eval: false
#| output: false

for (i in split(id_data, seq(nrow(id_data)))) {
  bundle_files <- c(
    "actigraphy-raw-data" = file.path(
      dir_raw_actigraphy, paste0(i$id, "_actigraphy-raw-data", ".txt")
    ),
    "actigraphy-raw-data_report" = file.path(
      dir_raw_actigraphy, paste0(i$id, "_actigraphy-raw-data-report", ".txt")
    ),
    "actigraphy-processed-data" = file.path(
      dir_processed_actigraphy, paste0(i$id, "_actigraphy-processed-data", ".txt")
    ),
    "actigraphy-sleep-diary" = file.path(
      dir_processed_actigraphy, paste0(i$id, "_actigraphy-sleep-diary", ".txt")
    ),
    "consent" = file.path(
      dir_raw_consent, paste0(i$id, "_consent", ".pdf")
    ),
    "delivery-receipt" = file.path(
      dir_raw_delivery_receipt, paste0(i$id, "_delivery-receipt", ".pdf")
    ),
    "field-form" = file.path(
      dir_raw_field_form, paste0(i$id, "_field-form", ".csv")
    ),
    "medical-record" = file.path(
      dir_raw_medical_record, paste0(i$id, "_medical-record", ".pdf")
    ),
    "pregnancy-booklet" = file.path(
      dir_raw_pregnancy_booklet, paste0(i$id, "_pregnancy-booklet", ".pdf")
    ),
    "return-receipt" = file.path(
      dir_raw_return_receipt, paste0(i$id, "_return-receipt", ".pdf")
    ),
    "sleep-diary" = file.path(
      dir_raw_sleep_diary, paste0(i$id, "_sleep-diary", ".csv")
    ),
    "sleep-diary-type-of-day" = file.path(
      dir_processed_sleep_diary, paste0(i$id, "_sleep-diary-type-of-day", ".csv")
    )
  )

  for (j in bundle_files) {
    if (!file.exists(j)) {
      bundle_files <- bundle_files[!bundle_files %in% j]
    }
  }

  if (!length(bundle_files) == 0) {
    utils::zip(
      zipfile = file.path(dir_bundles, i$id),
      files = bundle_files,
      flags = paste("--password", password),
      extras = "-j"
    )
  }
}
```
