---
execute:
  eval: false
---

# Birth Center Map

```{r}
#| label: setup
#| include: false

library(here)

source(here("R", "_setup.R"))
```

## Set the Environment

### Load Packages

```{r}
#| output: false

library(curl)
library(dplyr)
library(geobr)
library(ggplot2)
library(groomr)  # github.com/danielvartan/groomr
library(lubridate)
library(magick)
library(magrittr)
library(orbis) # github.com/danielvartan/orbis
library(ragg)
library(sf)
```

### Set Data Directories

```{r}
data_dir <- here("data", "geosampa")
images_dir <- here("images")
```

```{r}
for (i in c(data_dir, images_dir)) {
  if (!dir.exists(i)) dir.create(i)
}
```

### Set Initial Variables

```{r}
set.seed(2025)
```

```{r}
municipality <- 3550308 # São Paulo
```

### Set Birth Center Coordinates

```{r}
birth_center_coordinates <-
  tibble(
    name = c("Casa Angela", "Casa do Parto Sapopemba"),
    longitude = c(-46.73389, -46.5327),
    latitude = c(-23.64575, -23.60428)
  ) |>
  st_as_sf(
    coords = c("longitude", "latitude"),
    crs = st_crs("EPSG:4674")
  )
```

## Download and Import Municipality Subprefecture Shapes

Source: <https://geosampa.prefeitura.sp.gov.br/PaginasPublicas/_SBC.aspx>

```{r}
subprefecture_shapes <-
  here(data_dir, "geoportal_subprefeitura_v2.gpkg") |>
  st_read() |>
  select(nm_subprefeitura, ge_poligono) |>
  rename(name_subprefecture = nm_subprefeitura, geom = ge_poligono)
```

## Download and Import Municipality Districts Shapes

```{r}
districts_shapes <-
  read_neighborhood(year = 2010) |>
  filter(code_muni == municipality) |>
  select(name_district, geom)
```

## Plot Birth Center Map

```{r}
ggsave_mode <- TRUE

if (isTRUE(ggsave_mode)) {
  plot_params <- list(
    geom_sf_shape_size = 0.1,
    geom_sf_text_size_1 = 5,
    geom_sf_text_size_2 = 6,
    geom_sf_point_size = 1.5,
    position_y_nudge = 2000
  )
} else {
  plot_params <- list(
    geom_sf_shape_size = 0.3,
    geom_sf_text_size_1 = 2,
    geom_sf_text_size_2 = 3,
    geom_sf_point_size = 3,
    position_y_nudge = 2500
  )
}

dev.off()
```

```{r}
gplot() +
  geom_sf(
    data = subprefecture_shapes,
    fill = "gray90",
    color = "gray75",
    size = plot_params$geom_sf_shape_size
  ) +
  geom_sf_text(
    data =
      subprefecture_shapes |>
      # filter(
      #   case_when(
      #     as.numeric(st_area(geom)) < 50000000 &
      #       nchar(name_subprefecture) < 12 ~ TRUE,
      #     as.numeric(st_area(geom)) >= 100000000 &
      #       nchar(name_subprefecture) < 15 ~ TRUE,
      #     TRUE ~ FALSE
      #   ),
      mutate(
        name_subprefecture =
          name_subprefecture |>
          to_title_case_pt(),
        name_subprefecture = case_when(
            name_subprefecture == "Capela do Socorro" ~
              "Capela do\nSocorro",
            name_subprefecture == "Santo Amaro" ~
              "Santo\nAmaro",
            name_subprefecture == "M Boi Mirim" ~
              "M'Boi\nMirim",
            name_subprefecture == "Jacana-Tremembe" ~
              "Jacana-\nTremembé",
             name_subprefecture == "Se" ~
              "Sé",
             name_subprefecture == "Sao Mateus" ~
              "São Mateus",
             name_subprefecture == "Sao Miguel" ~
              "São Miguel",
             name_subprefecture == "Butanta" ~
              "Butantã",
            TRUE ~ name_subprefecture
          )
      ) |>
      filter(
        name_subprefecture |>
          is_in(
            c(
              # "Aricanduva-Formosa-Carrao",
              "Butantã",
              # "Campo Limpo",
              "Capela do\nSocorro",
              # "Casa Verde-Cachoeirinha",
              # "Cidade Ademar",
              # "Cidade Tiradentes",
              # "Ermelino Matarazzo",
              # "Freguesia-Brasilandia",
              # "Guaianases",
              # "Ipiranga",
              # "Itaim Paulista",
              "Itaquera",
              # "Jacana-\nTremembe",
              # "Jabaquara",
              "Lapa",
              "M'Boi\nMirim",
              "Mooca",
              "Parelheiros",
              "Penha",
              "Perus",
              # "Pinheiros",
              # "Pirituba-Jaragua",
              # "Santana-Tucuruvi",
              # "Sapopemba",
              "Santo\nAmaro",
              "São Mateus",
              "São Miguel",
              "Sé"
              # "Vila Maria-Vila Guilherme",
              # "Vila Mariana",
              # "Vila Prudente"
            )
          )
      ),
    aes(label = name_subprefecture),
    size = plot_params$geom_sf_text_size_1,
    color = "gray50"
  ) +
  geom_sf(
    data = birth_center_coordinates,
    color = "red",
    size = plot_params$geom_sf_point_size,
  ) +
  geom_sf_label(
    data = birth_center_coordinates ,
    aes(label = name),
    size = plot_params$geom_sf_text_size_2,
    fontface = "bold",
    position = position_nudge(y = plot_params$position_y_nudge),
    border.color = NA,
    text.color = "black"
  ) +
  coord_sf(datum = NA) +
  theme_void()
```

## Save Plot

```{r}
image_file <- here(images_dir, "birth-center-map-figure.png")
```

```{r}
image_file |>
  ggsave(
    plot = plot,
    device = agg_png(),
    width = 7,
    height = 10,
    units = "cm",
    dpi = 300,
    bg = "white",
    scale = 1
  )
```

```{r}
image_file |>
  image_read() |>
  image_trim() |>
  image_write(image_file)
```
