<!-- %:::% .common h1 begin %:::% -->
# Resumo {.unnumbered}
<!-- %:::% .common h1 end %:::% -->

```{r}
#| label: setup
#| include: false

source(here::here("R", "_setup.R"))
```

{{< var author-surname >}}, `r sub("\\. .\\.$", "", env_vars[["author-initials"]])`. ({{< var year >}}). *Associações entre a duração e a qualidade do sono de gestantes no terceiro trimestre com a duração do trabalho de parto* [Dissertação de Mestrado, Universidade de São Paulo].

::: {.content-visible when-format="pdf"}
<!-- %:::% foreign-abstract reference begin %:::% -->
Sales, A. R. V. ({\imprimirdata}). \textit{Associações entre a duração e a qualidade do sono de gestantes no terceiro trimestre com a duração do trabalho de parto} [Dissertação de Mestrado, Universidade de São Paulo].
<!-- %:::% foreign-abstract reference end %:::% -->
:::

<!-- %:::% foreign-abstract body begin %:::% -->
O texto abaixo está relacionado ao **projeto** desta dissertação. O resumo final só poderá ser produzido quando a pesquisa for finalizada.

Dentre as alterações biopsicossociais que ocorrem durante a gravidez estão as mudanças no padrão do ciclo sono-vigília. Pesquisas sugerem que há associações entre a duração e a qualidade do sono de gestantes no período pré-natal com desfechos adversos na saúde materno-infantil. O objetivo deste projeto é investigar a presença/ausência de associações significativas entre a duração e a qualidade do sono de gestantes no terceiro trimestre com a duração do trabalho de parto. Para isso, será realizado um estudo com 133 gestantes no terceiro trimestre gestacional acompanhadas em casas de parto do SUS, localizadas no município de São Paulo. Serão coletados dados sociodemográficos, antropométricos, obstétricos, actigráficos, dados relacionados ao sono e ao estado psicológico das participantes, além de dados secundários dos prontuários e cadernetas das gestantes. O estudo já obteve todas as aprovações éticas para sua operação por parte das autoridades competentes. Os resultados serão analisados pela comparação das médias entre grupos por meio de uma análise de covariância (ANCOVA). A hipótese é que uma menor qualidade e duração de sono no final do terceiro trimestre gestacional estão associadas a uma maior duração do trabalho de parto. Além de formar e capacitar profissionais e gerar conhecimento em um assunto de interesse público, espera-se que este estudo promova e contribua para o desenvolvimento de novos serviços e tecnologias de acompanhamento de gestantes, destacando a relevância do ciclo sono-vigília para a saúde materno-infantil.
<!-- %:::% foreign-abstract body end %:::% -->

**Palavras-chaves**: Gravidez. Parto. Parto Humanizado. Parto Natural. Duração do parto. Obstetrícia. Sono. Qualidade do sono. Duração do sono. Actigrafia. Cronobiologia.

::: {.content-visible when-format="pdf"}
<!-- %:::% foreign-abstract keywords begin %:::% -->
\begin{tabular}{p{3.6cm} p{12.3cm}}
  \textbf{Palavras-chaves}: & Gravidez. Parto. Parto Humanizado. Parto Natural.
    Duração do parto. Obstetrícia. Sono. Qualidade do sono. Duração do sono.
    Actigrafia. Cronobiologia.
\end{tabular}
<!-- %:::% foreign-abstract keywords end %:::% -->
:::
