---
execute:
  eval: false
---

# Extra – Download or Upload Files to OSF

```{r}
#| label: setup
#| include: false

source(here::here("R", "_setup.R"))
```

## Overview

This notebook aim to help download or upload files to OSF.

## Settings things up

```{r}
#| eval: false

library(clipr)
library(lubritime)
library(magrittr)
library(osfr)
library(readr)
library(utils)
```

```{r}
#| include: false

library(magrittr)
```

## Setting parameters

```{r}
#| eval: false

osf_pat <- askpass::askpass()
```

```{r}
#| eval: false

osfr::osf_auth(osf_pat)
```

```{r}
#| eval: false

private_key <- here::here("_ssh", "id_rsa")
```

```{r}
#| eval: false

public_key <- here::here("_ssh", "id_rsa.pub")
```

```{r}
#| eval: false

password <- askpass::askpass()
```

```{r}
osf_feedbacks_id <- "8hs7v"
osf_raw_data_id <- "7kg34"
osf_processed_data_id <- "a2dsw"
osf_bundles_id <- "fvh4u"
osf_pilot_data_id <- "tj5u2"
osf_tidy_data_id <- "npkjw"
```

## Downloading files

```{r}
#| eval: false

osf_id <-
  osf_raw_data_id %>%
  paste0("https://osf.io/", .)
```

```{r}
path <- "actigraphy" # default: NULL
type <- "file" # default: "any"
pattern <- "7cbf7851" # default: NULL (fixer — no regex)
```

```{r}
#| eval: false

files <-
  osf_id |>
  osfr::osf_retrieve_node() |>
  osfr::osf_ls_files(
    path = path,
    type = type,
    pattern = pattern,
    n_max = Inf
  ) |>
  osfr::osf_download(path = tempdir(), conflicts = "overwrite") |>
  magrittr::extract2("local_path")
```

```{r}
#| eval: false

unlocked_files <- character()

for (i in files) {
  i_path <- lockr::unlock_file(
    i,
    private_key = private_key,
    password = password
  )

  cli::cat_line()

  unlocked_files <- c(unlocked_files, i_path)
}
```

```{r}
#| eval: false

for (i in unlocked_files) {
  lockr::lock_file(
    i,
    public_key = public_key,
    remove_file = TRUE
  )

  cli::cat_line()
}
```

## Uploading files

```{r}
#| eval: false

osf_id <- osf_bundles_id
```

```{r}
#| eval: false

# Create the README.md file

readme_file <- tempdir() |> file.path("README.md")

c(
  "# {pregnancy}",
  "",
  "* All files were locked with the project's public key. Ask the project administrators for the key if you need access.",
  "",
  paste0("* Last update: ", lubritime::round_time(Sys.time()), ".")
) |>
  readr::write_lines(readme_file)

readr::read_lines(readme_file)
```

```{r}
#| eval: false

osf_id |>
  osfr::osf_retrieve_node() |>
  osfr::osf_upload(
    path = readme_file,
    conflicts = "overwrite",
    progress = TRUE
  )
```

```{r}
#| eval: false

path <- NULL # Use `NULL` to refer to the root.
```

```{r}
#| eval: false

osf_data <-
  osf_id |>
  osfr::osf_retrieve_node() |>
  osfr::osf_ls_files(
    path = path,
    n_max = Inf
  ) |>
  dplyr::arrange(name)

osf_data
```

```{r}
#| eval: false

dir_path <- clipr::read_clip() |> normalizePath("/", mustWork = FALSE)
```

```{r}
#| eval: false

files <-
  list.files(dir_path) |>
  paste0(".lockr") |>
  setdiff(osf_data$name) |>
  stringr::str_subset("^README", negate = TRUE) |>
  stringr::str_remove("\\.lockr$")

# files <- list.files(dir_path)

files
```

```{r}
#| eval: false

file.path(dir_path, files)|>
  vapply( prettycheck:::test_file_exists, logical(1)) |>
  unname()
```

```{r}
#| eval: false

files |> clipr::write_clip()
```

```{r}
new_files <- character()

for (i in seq_along(files)) {
  i_from <- file.path(dir_path, files[i])
  i_to <- file.path(tempdir(), files[i])

  test <- file.copy(from = i_from, to = i_to, overwrite = TRUE)

  if (isTRUE(test)) new_files <- c(new_files, i_to)
}

locked_files <- character()

for (i in new_files) {
  i_path <- lockr::lock_file(
    i,
    public_key = public_key,
    remove_file = TRUE
  )

  cli::cat_line()

  locked_files <- c(locked_files, i_path)
}
```

```{r}
#| eval: false

osf_id |>
  osfr::osf_retrieve_node() |>
  osfr::osf_upload(
    path = locked_files,
    conflicts = "overwrite",
    progress = TRUE
  )
```
