<!-- %:::% .common h1 begin %:::% -->
# Abstract {.unnumbered}
<!-- %:::% .common h1 end %:::% -->

```{r}
#| label: setup
#| include: false

source(here::here("R", "_setup.R"))
```

Sales, A. R. V. (`r env_vars[["year"]]`). *`r env_vars[["title"]] |> stringr::str_to_sentence()`* [`r env_vars[["academic-title"]]`'s `r env_vars[["type-of-work"]]`, `r env_vars[["university"]]`]. [https://doi.org/10.17605/OSF.IO/S4TBZ](https://doi.org/10.17605/OSF.IO/S4TBZ)

::: {.content-visible when-format="pdf"}
<!-- %:::% vernacular-abstract reference begin %:::% -->
Sales, A. R. V. ({\imprimirdata}). \textit{\imprimirtitulo} [{\imprimirtipodetituloacademico}'s {\imprimirtipotrabalho}, {\imprimiruniversidade}].
<!-- %:::% vernacular-abstract reference end %:::% -->
:::

<!-- %:::% vernacular-abstract body begin %:::% -->
The text below is related to the **project** of this thesis. The final abstract can only be produced when the research is completed.

Among the biopsychosocial changes that occur during pregnancy are alterations in the sleep-wake cycle pattern. Research suggests that there are associations between the duration and quality of sleep in pregnant women during the prenatal period and adverse maternal-infant health outcomes. The primary aim of this project is to investigate the presence/absence of significant associations between the duration and quality of sleep in pregnant women in the third trimester and the duration of labor. For this purpose, a study will be conducted with 133 pregnant women in the third trimester, followed up at SUS birthing centers located in the city of São Paulo. Demographic, anthropometric, obstetric, actigraphic, sleep-related, and psychological state data will be collected from the participants, in addition to secondary data from the women's medical records and prenatal books. The study has already obtained all necessary ethical approvals from the competent authorities. The results will be analyzed by comparing group means through an analysis of covariance (ANCOVA). The hypothesis is that poorer sleep quality and duration throughout pregnancy are associated with a longer duration of labor. In addition to training and capacitating professionals and generating knowledge on a public health issue, it is expected that this study will promote and contribute to the development of new services and technologies for monitoring pregnant women, highlighting the relevance of the sleep-wake cycle for maternal-infant health.
<!-- %:::% vernacular-abstract body end %:::% -->

**Keywords**: {{< var keyword >}}

::: {.content-visible when-format="pdf"}
<!-- %:::% vernacular-abstract keywords begin %:::% -->
\begin{tabular}{p{2.3cm} p{13.6cm}}
  \textbf{Keywords}: & Pregnancy. Childbirth. Humanizing Delivery.
  Natural Childbirth. Duration of childbirth. Obstetrics. Sleep.
  Sleep quality. Sleep Duration. Actigraphy. Chronobiology.
\end{tabular}
<!-- %:::% vernacular-abstract keywords end %:::% -->
:::
